PREFIX bot: <https://w3id.org/bot#>
PREFIX props: <http://lbd.arch.rwth-aachen.de/props#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (STRBEFORE(STR(?level), "-") AS ?levelValue) (SUM(xsd:decimal(STRBEFORE(STR(?area), "^^"))) AS ?totalArea)
WHERE {
    ?space a bot:Space ;
           props:area_property_simple ?area ;
           props:level_property_simple ?level .
}
GROUP BY ?level
ORDER BY ?level
